POST https://api.videosdk.live/ai/v1/ai-deployments
Authorization: {{$dotenv VIDEOSDK_TOKEN}}
Content-Type: application/json

{
    "name": "AI Whatsapp Agent",
    "description":"AI Telephony Agents - Inbound/Outbound Calls"
}