POST https://api.videosdk.live/ai/v1/ai-deployments
Authorization: VIDEOSDK_TOKEN
Content-Type: application/json

{
    "name": "Whatsapp AI Agent",
    "description":"AI Telephony Agents - Inbound/Outbound Calls"
}
